### ISSUE TITLE
Post Count shows Likes

### ISSUE THREAD

**Issue by Chew** [Chewsterchew/GotPvP-Notifier#1]
![untitled](https://cloud.githubusercontent.com/assets/8278263/15834871/20442d4e-2bf3-11e6-9cf5-02595df678d5.png)
I cannot figure out how to fix the issue.

**Comment by bcho04** [comment]
Have you checked lines 123-130 on **background.js**? It says "Posts" and "Likes". It may be possible that it moved the "Likes" (last part of line) on line 128 to the "posts" section on line 125.

**Comment by Chew** [comment]
Fixed in 0.4 thanks to Lintydude
